spring:
  application:
    name: catalog-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8021